"""add decisions column to meetings

Revision ID: 68643fed1869
Revises: a9b0a8a79b6f
Create Date: 2026-07-05 22:41:57.706387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68643fed1869'
down_revision: Union[str, Sequence[str], None] = 'a9b0a8a79b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('decisions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'decisions')
    # ### end Alembic commands ###
