"""add remaining AI output columns

Revision ID: 72b9c8643cd7
Revises: 64a3e7ea689e
Create Date: 2026-07-05 23:04:25.495331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b9c8643cd7'
down_revision: Union[str, Sequence[str], None] = '64a3e7ea689e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('key_discussion_points', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('risks', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('open_questions', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('follow_up_email', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('next_meeting_agenda', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('ai_title', sa.String(), nullable=True))
    op.add_column('meetings', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('category', sa.String(), nullable=True))
    op.add_column('meetings', sa.Column('sentiment', sa.String(), nullable=True))
    op.add_column('meetings', sa.Column('sentiment_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'sentiment_reason')
    op.drop_column('meetings', 'sentiment')
    op.drop_column('meetings', 'category')
    op.drop_column('meetings', 'tags')
    op.drop_column('meetings', 'ai_title')
    op.drop_column('meetings', 'next_meeting_agenda')
    op.drop_column('meetings', 'follow_up_email')
    op.drop_column('meetings', 'open_questions')
    op.drop_column('meetings', 'risks')
    op.drop_column('meetings', 'key_discussion_points')
    # ### end Alembic commands ###
